version: '2'
services:
  single-server-int:
    image: arangodb:3.4.6
    ports:
      - 8529:8529
    environment:
        - ARANGO_NO_AUTH=1
    volumes:
      - db:/var/lib/arangodb3
  sce-chrome:
    image: browserless/chrome
    ports:
      - 3000:3000
  sce-solr:
    image: registry.gitlab.com/sparkler-crawl-environment/sparkler/solr:memex-dd
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    command: ['/data/solr/bin/solr','start','-f']

  sce-splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050

  sce-api:
    image: registry.gitlab.com/sparkler-crawl-environment/memex-dd:memex-dd
    ports:
      - "5000:5000"
    environment:
      - WEBDRIVER_URL=http://sce-chrome:3000/webdriver
      - ARANGO_URL=http://single-server-int:8529
      - RUNNING_KUBERNETES=false
    command: ["./wait-for-it.sh", "single-server-int:8529", "--", "python", "run.py"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    

volumes:
 data:
 db:

